# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cbx-agent-k8sops.fullname" . }}-config
  labels:
    {{- include "cbx-agent-k8sops.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.agent.config.configYaml | nindent 4 }}
  mcp_config.json: |
    {
      "mcp_servers": {
        {{- range $name, $server := .Values.mcpConfig.servers }}
        "{{ $name }}": {
          "url": "{{ $server.url }}",
          "transport": "{{ $server.transport }}"
        }{{ if not (eq $name (keys $.Values.mcpConfig.servers | last)) }},{{ end }}
        {{- end }}
      }
    }