# templates/mcp-server-deployment.yaml
{{- if .Values.mcp_included }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cbx-agent-k8sops.fullname" . }}-mcp-server
  labels:
    {{- include "cbx-agent-k8sops.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cbx-agent-k8sops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp-server
  template:
    metadata:
      labels:
        {{- include "cbx-agent-k8sops.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mcp-server
    spec:
      containers:
        - name: mcp-server
          image: "{{ .Values.mcpServer.image.repository }}:{{ .Values.mcpServer.image.tag }}"
          imagePullPolicy: {{ .Values.mcpServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mcpServer.service.targetPort }}
              protocol: TCP
          env:
            - name: HOME
              value: "/home/appuser"
            - name: CBX_CONFIG_NAME
              value: "http"
          resources:
            {{- toYaml .Values.mcpServer.resources | nindent 12 }}
          volumeMounts:
            - name: mcp-config
              mountPath: /home/appuser/app_configs/mcp-config.yaml
              subPath: mcp-config.yaml
            - name: kubeconfig
              mountPath: /home/appuser/.kube/config
              subPath: config
              readOnly: true
            - name: argocd-config
              mountPath: /home/appuser/.config/argocd/config
              subPath: config
              readOnly: true
      volumes:
        - name: mcp-config
          configMap:
            name: {{ include "cbx-agent-k8sops.fullname" . }}-mcp-config
        - name: kubeconfig
          secret:
            secretName: {{ .Values.mcpServer.secretReferences.kubeconfig.secretName }}
        - name: argocd-config
          secret:
            secretName: {{ .Values.mcpServer.secretReferences.argocdConfig.secretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 