# values.yaml


# Agent configuration
agent:
  replicaCount: 1

  image:
    repository: ghcr.io/vkuusk/cbx-agent-k8sops
    tag: "v0.1.0"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    host: cbx-agent-k8sops.yourdomain.com  # Change this to your domain
    path: /
    pathType: Prefix

  # Secret references - these secrets must exist before deployment
  secretReferences:
    openaiApiKey:
      secretName: "cbx-agent-k8sops-openai-key"
      secretKey: "api-key"
      namespace: "cbx-agents"
    anthropicApiKey:
      secretName: "cbx-agent-k8sops-anthropic-key"
      secretKey: "api-key"
      namespace: "cbx-agents"

  # Configuration files for .k8sops directory
  config:
    configYaml: |
      default_model: openai/gpt-4.1-nano
      temperature: 0.1
      providers:
        ollama:
          base_url: http://localhost:11434

    mcpConfigJson: |
      {
        "mcp_servers": {
          "k8s_mcp": {
            "url": "http://cbx-agent-k8sops-mcp-server:8080/mcp/",
            "transport": "streamable_http"
          }
        }
      }

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# For agent and MCP server on the same cluster
mcpConfig:
  servers:
    k8s_mcp:
      url: "http://cbx-mcp-k8s.cbx-mcp-servers.svc.cluster.local:8080/mcp/"
      transport: "streamable_http"