# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cbx-mcp-server-k8s.fullname" . }}
  labels:
    {{- include "cbx-mcp-server-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "cbx-mcp-server-k8s.selectorLabels" . | nindent 4 }}
