services:
  cbx-agent-k8sops:
    image: ghcr.io/vkuusk/cbx-agent-k8sops:v0.1.0
    container_name: cbx-agent-k8sops
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ${K8SOPS_CONFIG_DIR:-~/.k8sops}:/root/.k8sops
    depends_on:
      - cbx-mcp-server-k8s

  cbx-mcp-server-k8s:
    image: ghcr.io/vkuusk/cbx-mcp-server-k8s:v0.1.0
    container_name: cbx-mcp-server-k8s
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ~/.kube:/home/appuser/.kube:ro
    environment:
      - K8S_CONTEXT=
      - K8S_NAMESPACE=default
      - K8S_MCP_TIMEOUT=300
      #- FASTMCP_TRANSPORT=streamable-http
      - K8S_MCP_TRANSPORT=streamable-http
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=8000
      - FASTMCP_JSON_RESPONSE=true
      - K8S_MCP_SECURITY_MODE=permissive


