services:
  cbx-agent-k8sops:
    image: ghcr.io/cembryonix/cbx-agent-k8sops:v0.1.1
    container_name: cbx-agent-k8sops
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ${K8SOPS_CONFIG_DIR:-~/.k8sops}:/root/.k8sops
    depends_on:
      - cbx-mcp-server-k8s

  cbx-mcp-server-k8s:
    image: ghcr.io/cembryonix/cbx-mcp-server-k8s:v0.1.1
    container_name: cbx-mcp-server-k8s
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ~/.kube:/home/appuser/.kube:ro
      - ~/.config/argocd:/home/appuser/.config/argocd:ro
    environment:
      - HOME=/home/appuser
    user: "${UID}:${GID}"


