apiVersion: v2
name: cbx-mcp-server-k8s
description: A Helm chart for CBX MCP Server for Kubernetes operations
type: application
version: 0.1.0
appVersion: "v0.1.1"
keywords:
  - mcp
  - kubernetes
  - operations
  - server
home: https://github.com/cembryonix/cbx-agent-k8sops
sources:
  - https://github.com/cembryonix/cbx-agent-k8sops
maintainers:
  - name: Cembryonix Team
    email: team@cembryonix.com
